### ISSUE TITLE
License

### ISSUE THREAD

**Issue by willbarkoff** [clintonhalpin/tabmonitor#1]
Hi,
I was wondering if it were possible for me to fork this extension, make some changes, and put it on the Chrome Web Store. I will credit you, but I didn't see a license so I was wondering if I was allowed to do this.
Thanks so much!

**Comment by clintonhalpin** [comment]
No problem go for it! Can you share when you publish?

**Comment by willbarkoff** [comment]
Sure! I will make sure to do so.
